### ISSUE TITLE
[Feature Request] Add search bar to Minion Admin site

### ISSUE THREAD

**Issue by rabbiveesh** [mojolicious/minion#104]
Currently, you can only filter the view of which jobs you want to say either by clicking one of the columns displayed, like queue or task name. Well, unless you type your search straight into the URL, that is.

It would be nice to have a search bar at the top of the page where you could search these things.

It would also be nice to have search suggestions as you type, like showing valid names for tasks (retrieved by `select task from minion_jobs group by task` or the like).

I would be happy to add this so long as I could use vue.js to implement it, and that it's something anyone else wants.

**Comment by kraih** [comment]
Probably related to #91.

**Comment by rabbiveesh** [comment]
Would happily do any and all search options. Though it makes the UX a harder question. 
At $work I usually make a text input with a dropdown next to it for choosing the search type.

**Comment by kraih** [comment]
On the use of vue.js, that's probably a no. I have no experience with it and couldn't maintain the code.

**Comment by kraih** [comment]
I just ran into this at work, having to look through a huge number of jobs. Some sort of search feature would have been very helpful.

**Comment by kraih** [comment]
I went with the most simplistic solution for now. https://github.com/mojolicious/minion/commit/084d89a96466d08bf85c87bfcdb69404c9d13130

**Comment by kraih** [comment]
The feature will definitely change, but we can just make iterative improvements.

**Comment by rabbiveesh** [comment]
The current implementation is surprising to me. If you leave `queue` or `note` empty, you get no results. I was expecting that  blank would mean include all.

**Comment by kraih** [comment]
Think i consider this done.
