### ISSUE TITLE
linkcheck doesn't work - links never checked

### ISSUE THREAD

**Issue by hussam-qasem** [mojolicious/minion#124]
* Mojolicious version: `9.31`
* Minion version: `10.25`
* Perl version: `v5.36.0`
* Operating system: `macOS 12.6.3 (21G419)`

### Steps to reproduce the behavior
1. Start a Postgres Database
```shell
docker run --rm --name postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 postgres:15.2
```

2. start [`linkcheck`](https://github.com/mojolicious/minion/tree/main/examples/linkcheck) Mojo App.
```shell
git clone https://github.com/mojolicious/minion/
cd minion/examples/linkcheck/
morbo script/linkcheck
```

3. Check the default URL (POST)
```shell
curl -X POST -F url=https://mojolicious.org/perldoc http://127.0.0.1:3000/links
```

4. Wait for results (GET)
```shell
for i in $(seq 1 10); do curl http://localhost:3000/links/1; sleep 3; done
```

### Expected behavior
Result should return

### Actual behavior
Result never returned. `LinkCheck::Task::CheckLinks::_check_links` never called.

### Test fails
```shell
TEST_ONLINE=postgresql://postgres@127.0.0.1:5432/postgres script/linkcheck test

Unknown command "test", maybe you need to install it?
```

**Comment by hussam-qasem** [comment]
I am sorry. I forgot to run a worker:
```shell
perl script/linkcheck minion worker
```

In docker environment, should the worker be running in a separate container though?

**Comment by kraih** [comment]
> In docker environment, should the worker be running in a separate container though?

Yes.

**Comment by hussam-qasem** [comment]
Thank you @kraih for the prompt response. I'm still unable to run the tests though:
```shell
TEST_ONLINE=postgresql://postgres@127.0.0.1:5432/postgres script/linkcheck test
```

**Comment by hussam-qasem** [comment]
> > ```shell
> > ...script/linkcheck test
> > ```
> 
> I have no idea what that is.

From the [test file](https://github.com/mojolicious/minion/blob/36b9a75918b1fc4128b6bade756d9afd8c28d649/examples/linkcheck/t/linkcheck.t#L7). I thought it was possible, other than `prove -lv`. Thank you!
