### ISSUE TITLE
Command::minion::worker doesn't offer a way for proper job cleanup

### ISSUE THREAD

**Issue by andrii-suse** [mojolicious/minion#134]
So, in typical scenario for custom minion worker- it inherits from `Command::minion::worker` and then calls `$self->SUPER::run(@args);`

Now when the worker code starts new job, it forks the process and starts performing the task. 

But there is no way for that job to make sure that it e.g. properly closes  DB connection or does any other cleanup job.

My proposal is to somehow provide a way for `Command::minion::worker` to pass custom cleanup emit function to all forked jobs (e.g. to make sure they close DB connection properly).

Without such functionality everyone who needs Job cleanup must duplicate code of `Command::minion::worker` instead of inheriting and reusing it.

**Comment by andrii-suse** [comment]
But we don't have access to the Minion::Worker instance in descendants of `Command::minion::worker`

**Comment by kraih** [comment]
Subclasses have access to `$self->app->minion`, which emits a `worker` event.

**Comment by andrii-suse** [comment]
You are fully right - that is something I forgot to consider.
Following worked out in test environment - closing, thx!

```
   $minion->on(
        worker => sub () {
            my (undef, $worker) = @_;
            $worker->on(
                dequeue => sub () {
                    my (undef, $job) = @_;
                    $job->on(
                        cleanup => sub () {
                            my ($j) = @_;
                            print STDERR "IN CLEANUP PID " . $$ . "...\n";
                            $j->app->schema->disconnect_db;
                            $j->app->minion->backend->mysql->close_idle_connections();
                            $j->app->minion->backend->mysql->db->disconnect();
                            print STDERR "CLENUPFINISHED FOR  PID " . $$ . "...\n";
                        }
                    );
                }
            );
        }
    );
    $self->SUPER::run(@args);
```

**Comment by kraih** [comment]
That does look like what i was expecting. Three levels of events is a bit deep, but at least it already works without code changes.

**Comment by jberger** [comment]
Yep, three layers, just like [Minion::Notifier](https://github.com/jberger/Minion-Notifier/blob/master/lib/Minion/Notifier.pm)
