### ISSUE TITLE
Help to upgrade MongoDB Backend 

### ISSUE THREAD

**Issue by EmilianoBruni** [mojolicious/minion#75]
I'm current trying to upgrade Minion::BackEnd::MongoDB backend (unmanteined from 2015) to support interface changes in Minion and MongoDB.

https://github.com/EmilianoBruni/Minion-Backend-MongoDB

At this time I was able to make work minion_bench.pl, linkcheck and most parts of admin interface but I have need to change Minion.pm code owing to a strange behaviour and I need some advices.

The problem is that when forks, mongodb client need to reconnect

https://metacpan.org/pod/MongoDB::MongoClient#THREAD-SAFETY-AND-FORK-SAFETY

So I need to intercept the worker forks.  The best way I thought it was to register the emit of dequeue worker in register_worker but here I have only the id of the worker. If you can send the worker object I can register this event there.

For now I  overloaded the minion method of Backened in this way

`sub minion {
  my ($self, $minion)      = @_;

  return $self->{minion} unless $minion;

  $self->{minion} = $minion;
  weaken $self->{minion};

  $minion->on(worker => sub {
      my ($minion, $worker) = @_;
      $worker->on(dequeue => sub { pop->once(spawn => \&_spawn) } );
  });
}
sub _spawn {
  my ($job, $pid) = @_;
  my ($id, $task) = ($job->id, $job->task);
  $job->minion->backend->mongodb->client->reconnect();
}
`

but  now, the problem. This method is called in Minion.pm with this one line code

`return $self->backend($class->new(@_)->minion($self));`

but, with this call, I find an empty minion object in my overloaded method ( `bless({}, Minion)` )

If I change your code exploding the one line code like this

`my $be = $class->new(@_); $be->minion($self); return $self->backend($be);`

all works fine. 

Can you help me to find where is the problem and oveloaded in the correct way the minion method so your one line code works?

Thanks in advance and sorry for my bad english

**Comment by kraih** [comment]
Looks like we are adding a new event in Mojolicious 8.10 you can use for this. https://github.com/mojolicious/mojo/commit/2edfdb2d2d53f5cd3a0c4609bbe1f9dcccd719ac

**Comment by EmilianoBruni** [comment]
Cool. It works well.

Last question. I'm new to IOLoop. I successfull intercept the reset event in `new` of my backend 
```perl
sub new {
  my ($class, $url) = @_;
  ...
  my $self = $class->SUPER::new(mongodb => $db);
  my $loop = Mojo::IOLoop->singleton;
  $loop->on(reset => sub {*
    $self->mongodb->client->reconnect();
  });
 return $self;
}
```

is this the right way?

**Comment by kraih** [comment]
Yes. In the future please try to use our official support channels for similar discussions, we only use GitHub for bugs normally. https://mojolicious.org/perldoc#SUPPORT
