### ISSUE TITLE
Admin UI could support usernames/passwords (feature request)

### ISSUE THREAD

**Issue by srchulo** [mojolicious/minion#77]
This is a feature request. It would be nice if there was a simple login page that came with the Admin UI so that usernames/passwords could come from the passed in config or a backend.

**Comment by jhthorsen** [comment]
I agree with @kraih.

**Comment by srchulo** [comment]
I agree, a third party plugin that already does the login would be good.

The reason I wanted this is that most of my use cases, the login is meant for the users of the site, so it feels a little unnatural to piggyback on that when really what I want is a login just for Minion. So I'm creating a login page/basic login code a few different places for different apps when I use Minion. I thought it could be convenient to have the login page bundled with Minion as a feature for the dashboard.

However, if you both don't think this is a good idea, feel free to close! It's not a ton of code that I have to write, and maybe I could just create something reusable myself, especially if others don't run into this much.

**Comment by srchulo** [comment]
> The problem is that there’s a bunch of ways to handle login, and storing username/passwords in a config file is not a very good idea.

Yeah, I guess I was just picturing something minimal since that's what I need, but your follow up point is good in that this could launch a bunch of other requests. If that's not the direction of the Admin UI, maybe it would make sense to either do nothing, or do whatever amount is appropriate and make clear in the documentation that Minion did a small amount for consistency, but it's not the direction of Minion to go further down that path.

However, it's always possible there are those who don't read the documentation or don't agree and then generate the requests you mentioned earlier :)
