### ISSUE TITLE
Please explain what should happen.

### ISSUE THREAD

**Issue by Skeeve** [mojolicious/minion#81]
When I do not have `scripts/myapp minion worker` running, I can see in SQLite DB' `minion_jobs` jobs queuing up.

When I start `scripts/myapp minion worker`, nothing happens to these jobs.

When I enqueu a new job while `scripts/myapp minion worker` is running, nothin appears in the job queue.

I just started to work with mojolicious/minion and so it's still quite unclear as what to provide in order to get help to see my lack of knowledge.

I took this linkercheck example as a boilerplate for my minion jobs. The only thing I'm doing inside the task is simply calling `$job->finished(\[])`, so nothing fancy which could make the thing crash or so.

**Comment by jberger** [comment]
Hi @Skeeve! We are happy to help you learn how to use mojolicious and minion, however we like to reserve the issue trackers for bug reports etc. Could you please join us on irc or on the mailing list? We'd be happy to chat with you there! https://mojolicious.org/perldoc#SUPPORT
