### ISSUE TITLE
Show how long each job has been running in the admin ui

### ISSUE THREAD

**Issue by kraih** [mojolicious/minion#83]
I'm not sure yet how to best integrate this into the admin ui. But i think it would be very useful to show how long active jobs have been running already, and how long finished/failed jobs have taken in the job list table. Perhaps a new column that stays empty for inactive jobs?

**Comment by coolo** [comment]
A tooltip sounds good enough for me actually. It's only useful for long running tasks in specific states.

**Comment by kraih** [comment]
Actually, i think i would like to be able to select all finished jobs of a certain type and see in the table which ones were the fastest and slowest.

**Comment by kraih** [comment]
Feature has been added. https://github.com/mojolicious/minion/commit/f2cea082f915af29a57d1f116a93cac47554eaf9
<img width="1200" alt="admin" src="https://user-images.githubusercontent.com/30094/60809609-5b8cf000-a18b-11e9-918b-2326eb43ea1a.png">
