### ISSUE TITLE
Minion::Admin can not remove retry inactive task 

### ISSUE THREAD

**Issue by ggmo** [mojolicious/minion#92]
Minion::Admin can not remove retry inactive task 

* Minion version:  10.04
* Perl version: 5.26.3 (activePerl linux)
* Operating system: centos 8
*Psql (PostgreSQL) 10.6

### Steps to reproduce the behavior
1、./manager minion job --remove 62 with CMD can remove the task , but with the web console can not remove tasks, also the chrome devtools can not get error info
2、web console can get data from pg, also execute the task with mojo;

plz help fix the bug

**Comment by ggmo** [comment]
also find the html have no url :


<form action="/minion/jobs">
--
  | <div class="d-flex justify-content-between">
  | <div>
  | <div class="btn-group" role="group">
  | <button class="btn btn-outline-secondary" name="do" value="retry"
  | type="submit">
  | <i class="fas fa-redo" aria-hidden="true"></i> Retry
  | </button>
  | <button class="btn btn-outline-secondary" name="do" value="stop"
  | type="submit">
  | <i class="fas fa-ban" aria-hidden="true"></i> Stop
  | </button>
  | <button class="btn btn-outline-secondary" name="do" value="remove"
  | type="submit">
  | <i class="fas fa-times" aria-hidden="true"></i> Remove
  | </button>
  | <button class="btn btn-outline-secondary dropdown-toggle" type="button"
  | id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true"
  | aria-expanded="false">
  | <i class="fas fa-traffic-light"></i> Signal
  | </button>
  | <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
  | <button class="dropdown-item" name="do" value="sig_int" type="submit">
  | INT
  | </button>
  | <button class="dropdown-item" name="do" value="sig_usr1"
  | type="submit">
  | USR1
  | </button>
  | <button class="dropdown-item" name="do" value="sig_usr2"
  | type="submit">
  | USR2
  | </button>
  | </div>
  | </div>
  | </div>
  | <p class="align-middle">
  | 1-9 of 9
  | </p>
  | <nav>

**Comment by kraih** [comment]
Deleting jobs from the admin ui works fine.

**Comment by ggmo** [comment]
https://metacpan.org/source/SRI/Minion-10.04/lib/Minion/Backend/Pg.pm

Is it possible to have something to do with this code ？ 
1、sub remove_job {
  !!shift->pg->db->query(
    "delete from minion_jobs
     where id = ? and state in ('inactive', 'failed', 'finished')
     returning 1", shift
  )->rows;
}

2、when i use restful api debugger , warn 404


Date: | Wed, 19 Feb 2020 10:25:51 GMT
-- | --
Access-Control-Allow-Origin: | http://192.168.100.100:8088
Access-Control-Allow-Credentials: | true
Content-Type: | text/html;charset=UTF-8
Access-Control-Allow-Methods: | GET, PUT, POST, DELETE, OPTIONS, PATCH
Server: | Mojolicious (Perl)
Access-Control-Max-Age: | 3600
Access-Control-Allow-Headers: | Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Authorization , Access-Control-Request-Headers
Content-Length: | 25 kilobytes

**Comment by ggmo** [comment]
I have uninstalled Mojo :: Pg Minion Mojolicious and reinstalled it, but I still can only receive jobs but cannot delete it. Pause Reopen inactive JOB, please give some advice ,many thanks!!!

**Comment by ggmo** [comment]
Some exceptions were found through the command line minion work --remove job

[2020-02-19 18:41:33.22526] [19871] [info] Creating Routes for resource 'Device' (controller => Device)
[2020-02-19 18:41:33.22547] [19871] [debug]  OPTIONS /mojo/devices  (api_options)
[2020-02-19 18:41:33.22559] [19871] [debug]  GET /mojo/devices  (api_get)
[2020-02-19 18:41:33.22569] [19871] [debug]  POST /mojo/devices  (api_create)
[2020-02-19 18:41:33.22578] [19871] [debug]  DELETE /mojo/devices/  (api_delete)
[2020-02-19 18:41:33.22592] [19871] [debug]  PUT /mojo/devices/  (api_update)
[2020-02-19 18:41:33.22619] [19871] [debug]  GET /mojo/devices/download  (api_download)
[2020-02-19 18:41:33.22647] [19871] [info] Creating Routes for resource 'Firewall' (controller => Firewall)
[2020-02-19 18:41:33.22673] [19871] [debug]  OPTIONS /mojo/firewalls  (api_options)
[2020-02-19 18:41:33.22693] [19871] [debug]  GET /mojo/firewalls  (api_get)
[2020-02-19 18:41:33.22709] [19871] [debug]  POST /mojo/firewalls  (api_create)
[2020-02-19 18:41:33.22724] [19871] [debug]  DELETE /mojo/firewalls/  (api_delete)
[2020-02-19 18:41:33.22734] [19871] [debug]  PUT /mojo/firewalls/  (api_update)
[2020-02-19 18:41:33.22749] [19871] [debug]  GET /mojo/firewalls/download  (api_download)
Job does not exist.
[root@careline script]# ./firewall_manager minion job --remove 78
**### 

- Odd number of elements in anonymous hash at (eval 90) line 2.

**

**Comment by kraih** [comment]
I double checked to make sure, and there is absolutely no problem removing inactive jobs with the admin ui.
