### ISSUE TITLE
action buttons don't perform their actions, only redirect

### ISSUE THREAD

**Issue by arhak** [mojolicious/minion#96]
* Minion version: 10.04
* Perl version: 5.28.1
* Operating system: Ubuntu 17

### Steps to reproduce the behavior
* try to stop or remove a job minion/jobs
* try to unlock a lock minion/locks

### Expected behavior
named action is performed: either job is stopped or removed, or lock is unlocked

### Actual behavior
action doesn't take place and list page is rendered again without any change
form method is GET by default and buttons type=submit don't change that
while routes are patch and delete, not get

routes:
```
  $prefix->get('/jobs'    => \&_list_jobs)->name('minion_jobs');
  $prefix->patch('/jobs' => \&_manage_jobs)->name('minion_manage_jobs');
  $prefix->get('/locks' => \&_list_locks)->name('minion_locks');
  $prefix->delete('/locks' => \&_unlock)->name('minion_unlock');
```

**Comment by kraih** [comment]
Then how do the tests pass?

**Comment by arhak** [comment]
haha, sorry, my bad
initialized the plugin under a get route
